# Docker Compose configuration for VisaPics production deployment

services:
  visapics:
    build:
      context: .
      dockerfile: Dockerfile.uv
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
    shm_size: 2G
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - MAIL_SERVER=${MAIL_SERVER:-smtp.gmail.com}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USE_TLS=${MAIL_USE_TLS:-True}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
      - ./previews:/app/previews
      - ./models:/app/models
      - ./gfpgan/weights:/app/gfpgan/weights
      - payment_db:/app/payment_data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - visapics
    restart: unless-stopped

volumes:
  payment_db: